// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prototype_server_client.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "prototype_server_client.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb_prototype {
namespace PS2C {
class WhoDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Who> {
} _Who_default_instance_;
class ChatDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Chat> {
} _Chat_default_instance_;
class AuthDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Auth> {
} _Auth_default_instance_;

namespace protobuf_prototype_5fserver_5fclient_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Who, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Who, message_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Chat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Chat, message_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Auth, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Auth, auth_result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Auth, player_unit_data_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Who)},
  { 6, -1, sizeof(Chat)},
  { 12, -1, sizeof(Auth)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Who_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Chat_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Auth_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "prototype_server_client.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _Who_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Chat_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _Auth_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::pb_prototype::protobuf_prototype_5fcommon_2eproto::InitDefaults();
  _Who_default_instance_.DefaultConstruct();
  _Chat_default_instance_.DefaultConstruct();
  _Auth_default_instance_.DefaultConstruct();
  _Auth_default_instance_.get_mutable()->player_unit_data_ = const_cast< ::pb_prototype::PlayerUnitData*>(
      ::pb_prototype::PlayerUnitData::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\035prototype_server_client.proto\022\021pb_prot"
      "otype.PS2C\032\026prototype_common.proto\"\026\n\003Wh"
      "o\022\017\n\007message\030\001 \001(\t\"\027\n\004Chat\022\017\n\007message\030\001 "
      "\001(\t\"S\n\004Auth\022\023\n\013auth_result\030\001 \001(\010\0226\n\020play"
      "er_unit_data\030\002 \001(\0132\034.pb_prototype.Player"
      "UnitData*0\n\016ProtocolNumber\022\010\n\004EWho\020\000\022\t\n\005"
      "EChat\020\001\022\t\n\005EAuth\020\002P\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 268);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "prototype_server_client.proto", &protobuf_RegisterTypes);
  ::pb_prototype::protobuf_prototype_5fcommon_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_prototype_5fserver_5fclient_2eproto

const ::google::protobuf::EnumDescriptor* ProtocolNumber_descriptor() {
  protobuf_prototype_5fserver_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_prototype_5fserver_5fclient_2eproto::file_level_enum_descriptors[0];
}
bool ProtocolNumber_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Who::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Who::Who()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_prototype_5fserver_5fclient_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb_prototype.PS2C.Who)
}
Who::Who(const Who& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  // @@protoc_insertion_point(copy_constructor:pb_prototype.PS2C.Who)
}

void Who::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

Who::~Who() {
  // @@protoc_insertion_point(destructor:pb_prototype.PS2C.Who)
  SharedDtor();
}

void Who::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Who::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Who::descriptor() {
  protobuf_prototype_5fserver_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_prototype_5fserver_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Who& Who::default_instance() {
  protobuf_prototype_5fserver_5fclient_2eproto::InitDefaults();
  return *internal_default_instance();
}

Who* Who::New(::google::protobuf::Arena* arena) const {
  Who* n = new Who;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Who::Clear() {
// @@protoc_insertion_point(message_clear_start:pb_prototype.PS2C.Who)
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Who::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb_prototype.PS2C.Who)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string message = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb_prototype.PS2C.Who.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb_prototype.PS2C.Who)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb_prototype.PS2C.Who)
  return false;
#undef DO_
}

void Who::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb_prototype.PS2C.Who)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb_prototype.PS2C.Who.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb_prototype.PS2C.Who)
}

::google::protobuf::uint8* Who::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb_prototype.PS2C.Who)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb_prototype.PS2C.Who.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb_prototype.PS2C.Who)
  return target;
}

size_t Who::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb_prototype.PS2C.Who)
  size_t total_size = 0;

  // string message = 1;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Who::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb_prototype.PS2C.Who)
  GOOGLE_DCHECK_NE(&from, this);
  const Who* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Who>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb_prototype.PS2C.Who)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb_prototype.PS2C.Who)
    MergeFrom(*source);
  }
}

void Who::MergeFrom(const Who& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb_prototype.PS2C.Who)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void Who::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb_prototype.PS2C.Who)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Who::CopyFrom(const Who& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb_prototype.PS2C.Who)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Who::IsInitialized() const {
  return true;
}

void Who::Swap(Who* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Who::InternalSwap(Who* other) {
  message_.Swap(&other->message_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Who::GetMetadata() const {
  protobuf_prototype_5fserver_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_prototype_5fserver_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Who

// string message = 1;
void Who::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Who::message() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PS2C.Who.message)
  return message_.GetNoArena();
}
void Who::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb_prototype.PS2C.Who.message)
}
#if LANG_CXX11
void Who::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb_prototype.PS2C.Who.message)
}
#endif
void Who::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb_prototype.PS2C.Who.message)
}
void Who::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb_prototype.PS2C.Who.message)
}
::std::string* Who::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:pb_prototype.PS2C.Who.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Who::release_message() {
  // @@protoc_insertion_point(field_release:pb_prototype.PS2C.Who.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Who::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.PS2C.Who.message)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Chat::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Chat::Chat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_prototype_5fserver_5fclient_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb_prototype.PS2C.Chat)
}
Chat::Chat(const Chat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  // @@protoc_insertion_point(copy_constructor:pb_prototype.PS2C.Chat)
}

void Chat::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

Chat::~Chat() {
  // @@protoc_insertion_point(destructor:pb_prototype.PS2C.Chat)
  SharedDtor();
}

void Chat::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Chat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Chat::descriptor() {
  protobuf_prototype_5fserver_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_prototype_5fserver_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Chat& Chat::default_instance() {
  protobuf_prototype_5fserver_5fclient_2eproto::InitDefaults();
  return *internal_default_instance();
}

Chat* Chat::New(::google::protobuf::Arena* arena) const {
  Chat* n = new Chat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Chat::Clear() {
// @@protoc_insertion_point(message_clear_start:pb_prototype.PS2C.Chat)
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Chat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb_prototype.PS2C.Chat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string message = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb_prototype.PS2C.Chat.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb_prototype.PS2C.Chat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb_prototype.PS2C.Chat)
  return false;
#undef DO_
}

void Chat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb_prototype.PS2C.Chat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb_prototype.PS2C.Chat.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb_prototype.PS2C.Chat)
}

::google::protobuf::uint8* Chat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb_prototype.PS2C.Chat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb_prototype.PS2C.Chat.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb_prototype.PS2C.Chat)
  return target;
}

size_t Chat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb_prototype.PS2C.Chat)
  size_t total_size = 0;

  // string message = 1;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Chat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb_prototype.PS2C.Chat)
  GOOGLE_DCHECK_NE(&from, this);
  const Chat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Chat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb_prototype.PS2C.Chat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb_prototype.PS2C.Chat)
    MergeFrom(*source);
  }
}

void Chat::MergeFrom(const Chat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb_prototype.PS2C.Chat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void Chat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb_prototype.PS2C.Chat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Chat::CopyFrom(const Chat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb_prototype.PS2C.Chat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Chat::IsInitialized() const {
  return true;
}

void Chat::Swap(Chat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Chat::InternalSwap(Chat* other) {
  message_.Swap(&other->message_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Chat::GetMetadata() const {
  protobuf_prototype_5fserver_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_prototype_5fserver_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Chat

// string message = 1;
void Chat::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Chat::message() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PS2C.Chat.message)
  return message_.GetNoArena();
}
void Chat::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb_prototype.PS2C.Chat.message)
}
#if LANG_CXX11
void Chat::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb_prototype.PS2C.Chat.message)
}
#endif
void Chat::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb_prototype.PS2C.Chat.message)
}
void Chat::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb_prototype.PS2C.Chat.message)
}
::std::string* Chat::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:pb_prototype.PS2C.Chat.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Chat::release_message() {
  // @@protoc_insertion_point(field_release:pb_prototype.PS2C.Chat.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Chat::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.PS2C.Chat.message)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Auth::kAuthResultFieldNumber;
const int Auth::kPlayerUnitDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Auth::Auth()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_prototype_5fserver_5fclient_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb_prototype.PS2C.Auth)
}
Auth::Auth(const Auth& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_player_unit_data()) {
    player_unit_data_ = new ::pb_prototype::PlayerUnitData(*from.player_unit_data_);
  } else {
    player_unit_data_ = NULL;
  }
  auth_result_ = from.auth_result_;
  // @@protoc_insertion_point(copy_constructor:pb_prototype.PS2C.Auth)
}

void Auth::SharedCtor() {
  ::memset(&player_unit_data_, 0, reinterpret_cast<char*>(&auth_result_) -
    reinterpret_cast<char*>(&player_unit_data_) + sizeof(auth_result_));
  _cached_size_ = 0;
}

Auth::~Auth() {
  // @@protoc_insertion_point(destructor:pb_prototype.PS2C.Auth)
  SharedDtor();
}

void Auth::SharedDtor() {
  if (this != internal_default_instance()) {
    delete player_unit_data_;
  }
}

void Auth::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Auth::descriptor() {
  protobuf_prototype_5fserver_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_prototype_5fserver_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Auth& Auth::default_instance() {
  protobuf_prototype_5fserver_5fclient_2eproto::InitDefaults();
  return *internal_default_instance();
}

Auth* Auth::New(::google::protobuf::Arena* arena) const {
  Auth* n = new Auth;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Auth::Clear() {
// @@protoc_insertion_point(message_clear_start:pb_prototype.PS2C.Auth)
  if (GetArenaNoVirtual() == NULL && player_unit_data_ != NULL) {
    delete player_unit_data_;
  }
  player_unit_data_ = NULL;
  auth_result_ = false;
}

bool Auth::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb_prototype.PS2C.Auth)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool auth_result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &auth_result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .pb_prototype.PlayerUnitData player_unit_data = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_player_unit_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb_prototype.PS2C.Auth)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb_prototype.PS2C.Auth)
  return false;
#undef DO_
}

void Auth::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb_prototype.PS2C.Auth)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool auth_result = 1;
  if (this->auth_result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->auth_result(), output);
  }

  // .pb_prototype.PlayerUnitData player_unit_data = 2;
  if (this->has_player_unit_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->player_unit_data_, output);
  }

  // @@protoc_insertion_point(serialize_end:pb_prototype.PS2C.Auth)
}

::google::protobuf::uint8* Auth::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb_prototype.PS2C.Auth)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool auth_result = 1;
  if (this->auth_result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->auth_result(), target);
  }

  // .pb_prototype.PlayerUnitData player_unit_data = 2;
  if (this->has_player_unit_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->player_unit_data_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb_prototype.PS2C.Auth)
  return target;
}

size_t Auth::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb_prototype.PS2C.Auth)
  size_t total_size = 0;

  // .pb_prototype.PlayerUnitData player_unit_data = 2;
  if (this->has_player_unit_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->player_unit_data_);
  }

  // bool auth_result = 1;
  if (this->auth_result() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Auth::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb_prototype.PS2C.Auth)
  GOOGLE_DCHECK_NE(&from, this);
  const Auth* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Auth>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb_prototype.PS2C.Auth)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb_prototype.PS2C.Auth)
    MergeFrom(*source);
  }
}

void Auth::MergeFrom(const Auth& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb_prototype.PS2C.Auth)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_player_unit_data()) {
    mutable_player_unit_data()->::pb_prototype::PlayerUnitData::MergeFrom(from.player_unit_data());
  }
  if (from.auth_result() != 0) {
    set_auth_result(from.auth_result());
  }
}

void Auth::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb_prototype.PS2C.Auth)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Auth::CopyFrom(const Auth& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb_prototype.PS2C.Auth)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Auth::IsInitialized() const {
  return true;
}

void Auth::Swap(Auth* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Auth::InternalSwap(Auth* other) {
  std::swap(player_unit_data_, other->player_unit_data_);
  std::swap(auth_result_, other->auth_result_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Auth::GetMetadata() const {
  protobuf_prototype_5fserver_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_prototype_5fserver_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Auth

// bool auth_result = 1;
void Auth::clear_auth_result() {
  auth_result_ = false;
}
bool Auth::auth_result() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PS2C.Auth.auth_result)
  return auth_result_;
}
void Auth::set_auth_result(bool value) {
  
  auth_result_ = value;
  // @@protoc_insertion_point(field_set:pb_prototype.PS2C.Auth.auth_result)
}

// .pb_prototype.PlayerUnitData player_unit_data = 2;
bool Auth::has_player_unit_data() const {
  return this != internal_default_instance() && player_unit_data_ != NULL;
}
void Auth::clear_player_unit_data() {
  if (GetArenaNoVirtual() == NULL && player_unit_data_ != NULL) delete player_unit_data_;
  player_unit_data_ = NULL;
}
const ::pb_prototype::PlayerUnitData& Auth::player_unit_data() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PS2C.Auth.player_unit_data)
  return player_unit_data_ != NULL ? *player_unit_data_
                         : *::pb_prototype::PlayerUnitData::internal_default_instance();
}
::pb_prototype::PlayerUnitData* Auth::mutable_player_unit_data() {
  
  if (player_unit_data_ == NULL) {
    player_unit_data_ = new ::pb_prototype::PlayerUnitData;
  }
  // @@protoc_insertion_point(field_mutable:pb_prototype.PS2C.Auth.player_unit_data)
  return player_unit_data_;
}
::pb_prototype::PlayerUnitData* Auth::release_player_unit_data() {
  // @@protoc_insertion_point(field_release:pb_prototype.PS2C.Auth.player_unit_data)
  
  ::pb_prototype::PlayerUnitData* temp = player_unit_data_;
  player_unit_data_ = NULL;
  return temp;
}
void Auth::set_allocated_player_unit_data(::pb_prototype::PlayerUnitData* player_unit_data) {
  delete player_unit_data_;
  player_unit_data_ = player_unit_data;
  if (player_unit_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.PS2C.Auth.player_unit_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace PS2C
}  // namespace pb_prototype

// @@protoc_insertion_point(global_scope)
