// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prototype_common.proto

#ifndef PROTOBUF_prototype_5fcommon_2eproto__INCLUDED
#define PROTOBUF_prototype_5fcommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace pb_prototype {
class NPCUnitData;
class NPCUnitDataDefaultTypeInternal;
extern NPCUnitDataDefaultTypeInternal _NPCUnitData_default_instance_;
class PlayerUnitData;
class PlayerUnitDataDefaultTypeInternal;
extern PlayerUnitDataDefaultTypeInternal _PlayerUnitData_default_instance_;
class UnitId;
class UnitIdDefaultTypeInternal;
extern UnitIdDefaultTypeInternal _UnitId_default_instance_;
}  // namespace pb_prototype

namespace pb_prototype {

namespace protobuf_prototype_5fcommon_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_prototype_5fcommon_2eproto

// ===================================================================

class UnitId : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_prototype.UnitId) */ {
 public:
  UnitId();
  virtual ~UnitId();

  UnitId(const UnitId& from);

  inline UnitId& operator=(const UnitId& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UnitId& default_instance();

  static inline const UnitId* internal_default_instance() {
    return reinterpret_cast<const UnitId*>(
               &_UnitId_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(UnitId* other);

  // implements Message ----------------------------------------------

  inline UnitId* New() const PROTOBUF_FINAL { return New(NULL); }

  UnitId* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UnitId& from);
  void MergeFrom(const UnitId& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UnitId* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 unit_type = 1;
  void clear_unit_type();
  static const int kUnitTypeFieldNumber = 1;
  ::google::protobuf::uint32 unit_type() const;
  void set_unit_type(::google::protobuf::uint32 value);

  // uint32 unit_id = 2;
  void clear_unit_id();
  static const int kUnitIdFieldNumber = 2;
  ::google::protobuf::uint32 unit_id() const;
  void set_unit_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb_prototype.UnitId)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 unit_type_;
  ::google::protobuf::uint32 unit_id_;
  mutable int _cached_size_;
  friend struct protobuf_prototype_5fcommon_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PlayerUnitData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_prototype.PlayerUnitData) */ {
 public:
  PlayerUnitData();
  virtual ~PlayerUnitData();

  PlayerUnitData(const PlayerUnitData& from);

  inline PlayerUnitData& operator=(const PlayerUnitData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerUnitData& default_instance();

  static inline const PlayerUnitData* internal_default_instance() {
    return reinterpret_cast<const PlayerUnitData*>(
               &_PlayerUnitData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PlayerUnitData* other);

  // implements Message ----------------------------------------------

  inline PlayerUnitData* New() const PROTOBUF_FINAL { return New(NULL); }

  PlayerUnitData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PlayerUnitData& from);
  void MergeFrom(const PlayerUnitData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PlayerUnitData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // .pb_prototype.UnitId unit_id = 1;
  bool has_unit_id() const;
  void clear_unit_id();
  static const int kUnitIdFieldNumber = 1;
  const ::pb_prototype::UnitId& unit_id() const;
  ::pb_prototype::UnitId* mutable_unit_id();
  ::pb_prototype::UnitId* release_unit_id();
  void set_allocated_unit_id(::pb_prototype::UnitId* unit_id);

  // @@protoc_insertion_point(class_scope:pb_prototype.PlayerUnitData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::pb_prototype::UnitId* unit_id_;
  mutable int _cached_size_;
  friend struct protobuf_prototype_5fcommon_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NPCUnitData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_prototype.NPCUnitData) */ {
 public:
  NPCUnitData();
  virtual ~NPCUnitData();

  NPCUnitData(const NPCUnitData& from);

  inline NPCUnitData& operator=(const NPCUnitData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NPCUnitData& default_instance();

  static inline const NPCUnitData* internal_default_instance() {
    return reinterpret_cast<const NPCUnitData*>(
               &_NPCUnitData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(NPCUnitData* other);

  // implements Message ----------------------------------------------

  inline NPCUnitData* New() const PROTOBUF_FINAL { return New(NULL); }

  NPCUnitData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NPCUnitData& from);
  void MergeFrom(const NPCUnitData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NPCUnitData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // .pb_prototype.UnitId unit_id = 1;
  bool has_unit_id() const;
  void clear_unit_id();
  static const int kUnitIdFieldNumber = 1;
  const ::pb_prototype::UnitId& unit_id() const;
  ::pb_prototype::UnitId* mutable_unit_id();
  ::pb_prototype::UnitId* release_unit_id();
  void set_allocated_unit_id(::pb_prototype::UnitId* unit_id);

  // @@protoc_insertion_point(class_scope:pb_prototype.NPCUnitData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::pb_prototype::UnitId* unit_id_;
  mutable int _cached_size_;
  friend struct protobuf_prototype_5fcommon_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UnitId

// uint32 unit_type = 1;
inline void UnitId::clear_unit_type() {
  unit_type_ = 0u;
}
inline ::google::protobuf::uint32 UnitId::unit_type() const {
  // @@protoc_insertion_point(field_get:pb_prototype.UnitId.unit_type)
  return unit_type_;
}
inline void UnitId::set_unit_type(::google::protobuf::uint32 value) {
  
  unit_type_ = value;
  // @@protoc_insertion_point(field_set:pb_prototype.UnitId.unit_type)
}

// uint32 unit_id = 2;
inline void UnitId::clear_unit_id() {
  unit_id_ = 0u;
}
inline ::google::protobuf::uint32 UnitId::unit_id() const {
  // @@protoc_insertion_point(field_get:pb_prototype.UnitId.unit_id)
  return unit_id_;
}
inline void UnitId::set_unit_id(::google::protobuf::uint32 value) {
  
  unit_id_ = value;
  // @@protoc_insertion_point(field_set:pb_prototype.UnitId.unit_id)
}

// -------------------------------------------------------------------

// PlayerUnitData

// .pb_prototype.UnitId unit_id = 1;
inline bool PlayerUnitData::has_unit_id() const {
  return this != internal_default_instance() && unit_id_ != NULL;
}
inline void PlayerUnitData::clear_unit_id() {
  if (GetArenaNoVirtual() == NULL && unit_id_ != NULL) delete unit_id_;
  unit_id_ = NULL;
}
inline const ::pb_prototype::UnitId& PlayerUnitData::unit_id() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PlayerUnitData.unit_id)
  return unit_id_ != NULL ? *unit_id_
                         : *::pb_prototype::UnitId::internal_default_instance();
}
inline ::pb_prototype::UnitId* PlayerUnitData::mutable_unit_id() {
  
  if (unit_id_ == NULL) {
    unit_id_ = new ::pb_prototype::UnitId;
  }
  // @@protoc_insertion_point(field_mutable:pb_prototype.PlayerUnitData.unit_id)
  return unit_id_;
}
inline ::pb_prototype::UnitId* PlayerUnitData::release_unit_id() {
  // @@protoc_insertion_point(field_release:pb_prototype.PlayerUnitData.unit_id)
  
  ::pb_prototype::UnitId* temp = unit_id_;
  unit_id_ = NULL;
  return temp;
}
inline void PlayerUnitData::set_allocated_unit_id(::pb_prototype::UnitId* unit_id) {
  delete unit_id_;
  unit_id_ = unit_id;
  if (unit_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.PlayerUnitData.unit_id)
}

// string name = 2;
inline void PlayerUnitData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PlayerUnitData::name() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PlayerUnitData.name)
  return name_.GetNoArena();
}
inline void PlayerUnitData::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb_prototype.PlayerUnitData.name)
}
#if LANG_CXX11
inline void PlayerUnitData::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb_prototype.PlayerUnitData.name)
}
#endif
inline void PlayerUnitData::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb_prototype.PlayerUnitData.name)
}
inline void PlayerUnitData::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb_prototype.PlayerUnitData.name)
}
inline ::std::string* PlayerUnitData::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:pb_prototype.PlayerUnitData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PlayerUnitData::release_name() {
  // @@protoc_insertion_point(field_release:pb_prototype.PlayerUnitData.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerUnitData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.PlayerUnitData.name)
}

// -------------------------------------------------------------------

// NPCUnitData

// .pb_prototype.UnitId unit_id = 1;
inline bool NPCUnitData::has_unit_id() const {
  return this != internal_default_instance() && unit_id_ != NULL;
}
inline void NPCUnitData::clear_unit_id() {
  if (GetArenaNoVirtual() == NULL && unit_id_ != NULL) delete unit_id_;
  unit_id_ = NULL;
}
inline const ::pb_prototype::UnitId& NPCUnitData::unit_id() const {
  // @@protoc_insertion_point(field_get:pb_prototype.NPCUnitData.unit_id)
  return unit_id_ != NULL ? *unit_id_
                         : *::pb_prototype::UnitId::internal_default_instance();
}
inline ::pb_prototype::UnitId* NPCUnitData::mutable_unit_id() {
  
  if (unit_id_ == NULL) {
    unit_id_ = new ::pb_prototype::UnitId;
  }
  // @@protoc_insertion_point(field_mutable:pb_prototype.NPCUnitData.unit_id)
  return unit_id_;
}
inline ::pb_prototype::UnitId* NPCUnitData::release_unit_id() {
  // @@protoc_insertion_point(field_release:pb_prototype.NPCUnitData.unit_id)
  
  ::pb_prototype::UnitId* temp = unit_id_;
  unit_id_ = NULL;
  return temp;
}
inline void NPCUnitData::set_allocated_unit_id(::pb_prototype::UnitId* unit_id) {
  delete unit_id_;
  unit_id_ = unit_id;
  if (unit_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.NPCUnitData.unit_id)
}

// string name = 2;
inline void NPCUnitData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NPCUnitData::name() const {
  // @@protoc_insertion_point(field_get:pb_prototype.NPCUnitData.name)
  return name_.GetNoArena();
}
inline void NPCUnitData::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb_prototype.NPCUnitData.name)
}
#if LANG_CXX11
inline void NPCUnitData::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb_prototype.NPCUnitData.name)
}
#endif
inline void NPCUnitData::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb_prototype.NPCUnitData.name)
}
inline void NPCUnitData::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb_prototype.NPCUnitData.name)
}
inline ::std::string* NPCUnitData::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:pb_prototype.NPCUnitData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NPCUnitData::release_name() {
  // @@protoc_insertion_point(field_release:pb_prototype.NPCUnitData.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NPCUnitData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.NPCUnitData.name)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace pb_prototype

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_prototype_5fcommon_2eproto__INCLUDED
