// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prototype_server_client.proto

#ifndef PROTOBUF_prototype_5fserver_5fclient_2eproto__INCLUDED
#define PROTOBUF_prototype_5fserver_5fclient_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "prototype_common.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)
namespace pb_prototype {
class NPCUnitData;
class NPCUnitDataDefaultTypeInternal;
extern NPCUnitDataDefaultTypeInternal _NPCUnitData_default_instance_;
class PlayerUnitData;
class PlayerUnitDataDefaultTypeInternal;
extern PlayerUnitDataDefaultTypeInternal _PlayerUnitData_default_instance_;
class UnitId;
class UnitIdDefaultTypeInternal;
extern UnitIdDefaultTypeInternal _UnitId_default_instance_;
namespace PS2C {
class Auth;
class AuthDefaultTypeInternal;
extern AuthDefaultTypeInternal _Auth_default_instance_;
class Chat;
class ChatDefaultTypeInternal;
extern ChatDefaultTypeInternal _Chat_default_instance_;
class Who;
class WhoDefaultTypeInternal;
extern WhoDefaultTypeInternal _Who_default_instance_;
}  // namespace PS2C
}  // namespace pb_prototype

namespace pb_prototype {
namespace PS2C {

namespace protobuf_prototype_5fserver_5fclient_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_prototype_5fserver_5fclient_2eproto

enum ProtocolNumber {
  EWho = 0,
  EChat = 1,
  EAuth = 2,
  ProtocolNumber_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ProtocolNumber_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ProtocolNumber_IsValid(int value);
const ProtocolNumber ProtocolNumber_MIN = EWho;
const ProtocolNumber ProtocolNumber_MAX = EAuth;
const int ProtocolNumber_ARRAYSIZE = ProtocolNumber_MAX + 1;

const ::google::protobuf::EnumDescriptor* ProtocolNumber_descriptor();
inline const ::std::string& ProtocolNumber_Name(ProtocolNumber value) {
  return ::google::protobuf::internal::NameOfEnum(
    ProtocolNumber_descriptor(), value);
}
inline bool ProtocolNumber_Parse(
    const ::std::string& name, ProtocolNumber* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ProtocolNumber>(
    ProtocolNumber_descriptor(), name, value);
}
// ===================================================================

class Who : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_prototype.PS2C.Who) */ {
 public:
  Who();
  virtual ~Who();

  Who(const Who& from);

  inline Who& operator=(const Who& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Who& default_instance();

  static inline const Who* internal_default_instance() {
    return reinterpret_cast<const Who*>(
               &_Who_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Who* other);

  // implements Message ----------------------------------------------

  inline Who* New() const PROTOBUF_FINAL { return New(NULL); }

  Who* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Who& from);
  void MergeFrom(const Who& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Who* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:pb_prototype.PS2C.Who)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend struct protobuf_prototype_5fserver_5fclient_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Chat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_prototype.PS2C.Chat) */ {
 public:
  Chat();
  virtual ~Chat();

  Chat(const Chat& from);

  inline Chat& operator=(const Chat& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Chat& default_instance();

  static inline const Chat* internal_default_instance() {
    return reinterpret_cast<const Chat*>(
               &_Chat_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Chat* other);

  // implements Message ----------------------------------------------

  inline Chat* New() const PROTOBUF_FINAL { return New(NULL); }

  Chat* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Chat& from);
  void MergeFrom(const Chat& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Chat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:pb_prototype.PS2C.Chat)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend struct protobuf_prototype_5fserver_5fclient_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Auth : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_prototype.PS2C.Auth) */ {
 public:
  Auth();
  virtual ~Auth();

  Auth(const Auth& from);

  inline Auth& operator=(const Auth& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Auth& default_instance();

  static inline const Auth* internal_default_instance() {
    return reinterpret_cast<const Auth*>(
               &_Auth_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Auth* other);

  // implements Message ----------------------------------------------

  inline Auth* New() const PROTOBUF_FINAL { return New(NULL); }

  Auth* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Auth& from);
  void MergeFrom(const Auth& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Auth* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .pb_prototype.PlayerUnitData player_unit_data = 2;
  bool has_player_unit_data() const;
  void clear_player_unit_data();
  static const int kPlayerUnitDataFieldNumber = 2;
  const ::pb_prototype::PlayerUnitData& player_unit_data() const;
  ::pb_prototype::PlayerUnitData* mutable_player_unit_data();
  ::pb_prototype::PlayerUnitData* release_player_unit_data();
  void set_allocated_player_unit_data(::pb_prototype::PlayerUnitData* player_unit_data);

  // bool auth_result = 1;
  void clear_auth_result();
  static const int kAuthResultFieldNumber = 1;
  bool auth_result() const;
  void set_auth_result(bool value);

  // @@protoc_insertion_point(class_scope:pb_prototype.PS2C.Auth)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::pb_prototype::PlayerUnitData* player_unit_data_;
  bool auth_result_;
  mutable int _cached_size_;
  friend struct protobuf_prototype_5fserver_5fclient_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Who

// string message = 1;
inline void Who::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Who::message() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PS2C.Who.message)
  return message_.GetNoArena();
}
inline void Who::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb_prototype.PS2C.Who.message)
}
#if LANG_CXX11
inline void Who::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb_prototype.PS2C.Who.message)
}
#endif
inline void Who::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb_prototype.PS2C.Who.message)
}
inline void Who::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb_prototype.PS2C.Who.message)
}
inline ::std::string* Who::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:pb_prototype.PS2C.Who.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Who::release_message() {
  // @@protoc_insertion_point(field_release:pb_prototype.PS2C.Who.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Who::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.PS2C.Who.message)
}

// -------------------------------------------------------------------

// Chat

// string message = 1;
inline void Chat::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Chat::message() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PS2C.Chat.message)
  return message_.GetNoArena();
}
inline void Chat::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb_prototype.PS2C.Chat.message)
}
#if LANG_CXX11
inline void Chat::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb_prototype.PS2C.Chat.message)
}
#endif
inline void Chat::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb_prototype.PS2C.Chat.message)
}
inline void Chat::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb_prototype.PS2C.Chat.message)
}
inline ::std::string* Chat::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:pb_prototype.PS2C.Chat.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Chat::release_message() {
  // @@protoc_insertion_point(field_release:pb_prototype.PS2C.Chat.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Chat::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.PS2C.Chat.message)
}

// -------------------------------------------------------------------

// Auth

// bool auth_result = 1;
inline void Auth::clear_auth_result() {
  auth_result_ = false;
}
inline bool Auth::auth_result() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PS2C.Auth.auth_result)
  return auth_result_;
}
inline void Auth::set_auth_result(bool value) {
  
  auth_result_ = value;
  // @@protoc_insertion_point(field_set:pb_prototype.PS2C.Auth.auth_result)
}

// .pb_prototype.PlayerUnitData player_unit_data = 2;
inline bool Auth::has_player_unit_data() const {
  return this != internal_default_instance() && player_unit_data_ != NULL;
}
inline void Auth::clear_player_unit_data() {
  if (GetArenaNoVirtual() == NULL && player_unit_data_ != NULL) delete player_unit_data_;
  player_unit_data_ = NULL;
}
inline const ::pb_prototype::PlayerUnitData& Auth::player_unit_data() const {
  // @@protoc_insertion_point(field_get:pb_prototype.PS2C.Auth.player_unit_data)
  return player_unit_data_ != NULL ? *player_unit_data_
                         : *::pb_prototype::PlayerUnitData::internal_default_instance();
}
inline ::pb_prototype::PlayerUnitData* Auth::mutable_player_unit_data() {
  
  if (player_unit_data_ == NULL) {
    player_unit_data_ = new ::pb_prototype::PlayerUnitData;
  }
  // @@protoc_insertion_point(field_mutable:pb_prototype.PS2C.Auth.player_unit_data)
  return player_unit_data_;
}
inline ::pb_prototype::PlayerUnitData* Auth::release_player_unit_data() {
  // @@protoc_insertion_point(field_release:pb_prototype.PS2C.Auth.player_unit_data)
  
  ::pb_prototype::PlayerUnitData* temp = player_unit_data_;
  player_unit_data_ = NULL;
  return temp;
}
inline void Auth::set_allocated_player_unit_data(::pb_prototype::PlayerUnitData* player_unit_data) {
  delete player_unit_data_;
  player_unit_data_ = player_unit_data;
  if (player_unit_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pb_prototype.PS2C.Auth.player_unit_data)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace PS2C
}  // namespace pb_prototype

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pb_prototype::PS2C::ProtocolNumber> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pb_prototype::PS2C::ProtocolNumber>() {
  return ::pb_prototype::PS2C::ProtocolNumber_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_prototype_5fserver_5fclient_2eproto__INCLUDED
